// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-CujKj5VfLA_0t5OHXeuDN4Z6Lpzzbls',
    appId: '1:651106676665:web:345dd6a9abd69fce05d068',
    messagingSenderId: '651106676665',
    projectId: 'stocks-data-app',
    authDomain: 'stocks-data-app.firebaseapp.com',
    databaseURL: 'https://stocks-data-app-default-rtdb.firebaseio.com',
    storageBucket: 'stocks-data-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUOrXmZYbdTfWcKWwXnzDbC30aKcmnGA',
    appId: '1:651106676665:android:67bbcbe8e6d65aff05d068',
    messagingSenderId: '651106676665',
    projectId: 'stocks-data-app',
    databaseURL: 'https://stocks-data-app-default-rtdb.firebaseio.com',
    storageBucket: 'stocks-data-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOnzXmTUL4E4aEicTznoT80PNn1EHVWpM',
    appId: '1:651106676665:ios:dd3e105005c762be05d068',
    messagingSenderId: '651106676665',
    projectId: 'stocks-data-app',
    databaseURL: 'https://stocks-data-app-default-rtdb.firebaseio.com',
    storageBucket: 'stocks-data-app.appspot.com',
    androidClientId: '651106676665-1scg97dljig7m527thehk0pngkq4mfnu.apps.googleusercontent.com',
    iosClientId: '651106676665-464pegnm5v9v7ij6nbp6d13ndkpo1jsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockDataApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOnzXmTUL4E4aEicTznoT80PNn1EHVWpM',
    appId: '1:651106676665:ios:dd3e105005c762be05d068',
    messagingSenderId: '651106676665',
    projectId: 'stocks-data-app',
    databaseURL: 'https://stocks-data-app-default-rtdb.firebaseio.com',
    storageBucket: 'stocks-data-app.appspot.com',
    androidClientId: '651106676665-1scg97dljig7m527thehk0pngkq4mfnu.apps.googleusercontent.com',
    iosClientId: '651106676665-464pegnm5v9v7ij6nbp6d13ndkpo1jsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockDataApp3',
  );
}
